#define USE_MATH_DEFINES

#include "basemap.h"

Basemap::Basemap()
{
	constexpr char symbols[HEIGHT][WIDTH + 1] = {
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLLSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSLMLLLSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLLLLMLLSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLLMMMMLSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSLLLLLLMMLLSSSSSS",
		"SSSSSSSSSSSSSSSLLLSSSSSSSSSLLLLLLLLLLLSSSSSS",
		"SSSSSSSSSSSSSLLLLLLLSSSSSSLLLLLLLLLLLLLLSSSS",
		"SSSSSSSSSSSSSLLLLLLLSSSSSSLLLLLMMMLLLLLSSSSS",
		"SSSSSSSSSSSSSSLLLLLLLLLLSLLLMMLMMMLLLLLSSSSS",
		"SSSSSSSSSSSSSSLLLLLLLLLLLLLMMMMMMMLLLLLLSSSS",
		"SSSSMMLLSSSSSSSLLLLLLLLLLLLMMMMLMLLLLLLLLSSS",
		"SSSLMMMMLLSSSSSLLLLLLLLLLLLLMMLLLLLLLLLLLSSS",
		"SSSLLLLMLSSSSSSLLLLLLLLLLLLLLLLLLLLLLLLSSSSS",
		"SSSLLMLLMSSSSSSLLLLLLLLLLSSSSSLLLLLLLLLSSSSS",
		"SSLLLMLSLSSSSSLLLLLLLLLSSSSSSSSSSSLLLLLSSSSS",
		"SLLLLMMSSSSMLLLLLLLLLSSSSSSSSSSSSSLLLSSSSSSS",
		"SSLLSSSSSSSSMLLLLLLLLSSSSSSSSSSSSSLSSSSSSSSS",
		"SSSSSSSSSSSSSLLLLLLLSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSLMMMLLSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSMMLSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS",
		"SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS"
	};
	for (int y = 0; y < HEIGHT; y++) for (int x = 0; x < WIDTH; x++) terrain[y][x] = symbols[y][x];
}